# 9.2 Numpy의 기초
## Numpy 배열

In [1]:
#p144
x = [1, 3, 5]
x.mean()

AttributeError: 'list' object has no attribute 'mean'

In [2]:
import numpy as np
x = np.array([1, 3, 5])
print(x.mean())

3.0


In [3]:
print(x.shape)

(3,)


In [4]:
#p145
a = np.array([[1, 2, 3], [2, 3, 4]])

In [5]:
x = np.array([1, 3, 5])
x = np.array(1, 3, 5)

ValueError: only 2 non-keyword arguments accepted

In [6]:
x = np.array([1, 3, 5, 7, 9, 11]).reshape(3, 2)
print(x)

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [7]:
y = np.ones([3, 4])
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
#p146
x = np.array([[1, 3, 5], [2, 4, 6]])
print(x[1])          # [2 4 6] 출력
print(x[1].mean())   # 4.0 출력
print(x.mean())      # 3.5 출력
print(x.shape)       # (2, 3) 출력

[2 4 6]
4.0
3.5
(2, 3)


## Numpy 배열의 슬라이싱

In [9]:
list1 = [[1, 11], [2, 12], [3, 13]]
print(list1[:][1])

[2, 12]


In [10]:
print(list1[:, 1])  # Error 발생

TypeError: list indices must be integers or slices, not tuple

In [11]:
#p147
import numpy as np
list1 = [[1, 11], [2, 12], [3, 13]]
np_ary = np.array(list1)
print(np_ary[:, 1])

[11 12 13]


In [12]:
import numpy as np
list1 = [[1, 11], [2, 12], [3, 13]]
print(np.array(list1[:, 1]))

TypeError: list indices must be integers or slices, not tuple

In [13]:
import numpy as np
list1 = np.array([[1, 11], [2, 12], [3, 13]])
print(list1[:, 1])

[11 12 13]


In [14]:
import numpy as np
list1 = [[1, 11], [2, 12], [3, 13]]
print(np.array(list1[:, 1]))

TypeError: list indices must be integers or slices, not tuple

## Numpy를 이용한 연산

In [15]:
#p148
import math
math.sqrt(2)

1.4142135623730951

In [16]:
math.sqrt([2, 3, 4])

TypeError: must be real number, not list

In [17]:
import numpy as np
np.sqrt([2, 3, 4])

array([1.41421356, 1.73205081, 2.        ])

In [18]:
#p149
math.sqrt([2, 3, 4])

TypeError: must be real number, not list

In [19]:
import numpy as np
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [20]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## 제로 벡터와 제로 행렬

In [21]:
#p150
import numpy as np
zero_vector = np.zeros(3)
print(zero_vector)

[0. 0. 0.]


In [22]:
zero_matrix = np.zeros((4, 3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
zero_vector = np.zeros(5)
zero_vector

array([0., 0., 0., 0., 0.])

In [24]:
zero_matrix = np.zeros((5, 3))
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
import numpy as np
my_array = np.zeros(15).reshape(3,5)
my_array += 4
my_array

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

## 전치행렬

In [26]:
#p151
ary = [[1,2], [3,4]]
print(ary.transpose())

AttributeError: 'list' object has no attribute 'transpose'

In [27]:
import numpy as np
ary = np.array([[1, 2], [3, 4]])
print(ary.transpose())

[[1 3]
 [2 4]]


In [28]:
#p152
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])
z = x * y
print(z)

[ 4 10 18]


In [29]:
s = [1, 2, 3]
t = s + 1
print(t)

TypeError: can only concatenate list (not "int") to list

In [30]:
s = np.array([1, 2, 3])
t = s + 1
print(t)

[2 3 4]


In [31]:
#p153
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(X[1])
print(X[:, 1])

[4 5 6]
[2 5 8]


In [32]:
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Y = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])
print(X[:,1]+Y[:,1])

[ 5 11 17]


In [33]:
#p154
a = np.array([10, 20, 30, 40, 50, 60, 70])
i = [1, 3, 5]
print(a[i])

[20 40 60]


In [34]:
#p155
import numpy as np
a = np.array([10, 20, 30, 40, 50, 60, 70])
b = np.array(a[1:6:2])
print('b:', b)
b[1] = 10
print('b:', b)
print('a:', a)
type(b)

b: [20 40 60]
b: [20 10 60]
a: [10 20 30 40 50 60 70]


numpy.ndarray

## 불리언

In [35]:
a = np.array([10, 20, 30, 40, 50, 60, 70])
b = a > 50
print(b)

[False False False False False  True  True]


In [36]:
ary = np.random.random(5)
print(ary)
print(np.all(ary >= 0.3))
print(np.any(ary > 0.7))

[0.8865313  0.89304575 0.28986496 0.40355656 0.06600076]
False
True


## 등간격 나누기

In [37]:
#p157
np.linspace(0, 12, 4)

array([ 0.,  4.,  8., 12.])

In [38]:
np.linspace(0, 12, 4, retstep=True)

(array([ 0.,  4.,  8., 12.]), 4.0)

In [39]:
np.linspace(0, 12, 4, endpoint=False)

array([0., 3., 6., 9.])

In [40]:
np.logspace(np.log10(10), np.log10(100), 5)

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

In [41]:
np.logspace(1, 2, 5)

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])